name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate as @ohmyzsh
        id: generate_token
        uses: ohmyzsh/github-app-token@v2
        with:
          app_id: ${{ secrets.OHMYZSH_APP_ID }}
          private_key: ${{ secrets.OHMYZSH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
      - name: Set up .wiki remote
        run: git remote add dot-wiki https://github.com/ohmyzsh/ohmyzsh.wiki.git
      - name: Push commits to main wiki remote
        run: git push --force dot-wiki HEAD:master
